# Notes:
#  recordSize can be 24, 28, or 32. Increase it if it fails.
databases:
  ## Start of CC0 Country DBs
  - name: "IPv4 - CC0"
    mmdb:
      ipVersion: 4
      recordSize: 24
    types:
      "country.iso_code": string
      "autonomous_system_organization": string
      "autonomous_system_number": uint32
    inputs:
      - file: "DBs/geo-whois-asn-country-ipv4.csv"
        fields: ["from", "to", "country.iso_code"]
    output: build/geoip-cc0-v4.mmdb
    optimize:
      floatDecimals: 3
      forceIPVersion: true
      maxPrefix: 0

  - name: "IPv6 - CC0"
    mmdb:
      ipVersion: 6
      recordSize: 24
    types:
      "country.iso_code": string
      "autonomous_system_organization": string
      "autonomous_system_number": uint32
    inputs:
      - file: "DBs/geo-whois-asn-country-ipv6.csv"
        fields: ["from", "to", "country.iso_code"]
    output: build/geoip-cc0-v6.mmdb
    optimize:
      floatDecimals: 3
      forceIPVersion: true
      maxPrefix: 0

  ## Start of PDDL ASN DBs
  - name: "IPv4 - PDDL - ASN"
    mmdb:
      ipVersion: 4
      recordSize: 24
    types:
      "country.iso_code": string
      "autonomous_system_organization": string
      "autonomous_system_number": uint32
    inputs:
      - file: "DBs/iptoasn-asn-ipv4.csv"
        fields: ["from", "to", "autonomous_system_number", "autonomous_system_organization"]
    output: build/geoip-pddl-asn-v4.mmdb
    optimize:
      floatDecimals: 3
      forceIPVersion: true
      maxPrefix: 0

  - name: "IPv6 - PDDL - ASN"
    mmdb:
      ipVersion: 6
      recordSize: 24
    types:
      "country.iso_code": string
      "autonomous_system_organization": string
      "autonomous_system_number": uint32
    inputs:
      - file: "DBs/iptoasn-asn-ipv6.csv"
        fields: ["from", "to", "autonomous_system_number", "autonomous_system_organization"]
    output: build/geoip-pddl-asn-v6.mmdb
    optimize:
      floatDecimals: 3
      forceIPVersion: true
      maxPrefix: 0

  ## Start of PDDL Country DBs
  - name: "IPv4 - PDDL - Country"
    mmdb:
      ipVersion: 4
      recordSize: 24
    types:
      "country.iso_code": string
      "autonomous_system_organization": string
      "autonomous_system_number": uint32
    inputs:
      - file: "DBs/iptoasn-country-ipv4.csv"
        fields: ["from", "to", "country.iso_code"]
    output: build/geoip-pddl-country-v4.mmdb
    optimize:
      floatDecimals: 3
      forceIPVersion: true
      maxPrefix: 0

  - name: "IPv6 - PDDL - Country"
    mmdb:
      ipVersion: 6
      recordSize: 24
    types:
      "country.iso_code": string
      "autonomous_system_organization": string
      "autonomous_system_number": uint32
    inputs:
      - file: "DBs/iptoasn-country-ipv6.csv"
        fields: ["from", "to", "country.iso_code"]
    output: build/geoip-pddl-country-v6.mmdb
    optimize:
      floatDecimals: 3
      forceIPVersion: true
      maxPrefix: 0
