name: Perform Tests

on:
  workflow_run:
    workflows: [Automated Build]
    types: [completed]

# IPv6 DBs take a long time to test. IPv4 however, is really quick
env:
  TEST_IPV6: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download Databases
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Download Tools
        uses: actions/download-artifact@v3
        with:
          name: tools

      - run: |
          chmod +x mmdbcheck

      - name: Test IPv4 DBs
        run: |
          find . -type f -name "*v4*.mmdb" -print | while read -r file; do
            ./mmdbcheck all $file
          done

      - name: Test IPv6 DBs
        if: ${{ env.TEST_IPV6 }}
        run: |
          find . -type f -name "*v6*.mmdb" -print | while read -r file; do
            ./mmdbcheck all $file
          done
